Repository theepiccode/Awesome-CyberSec-Resources, pull requests merged in 2021-10, with the labels that each got.

#48 updated some typing errors.
  README.md
Labels: feature :rocket:, hacktoberfest-accepted

#52 Adding enumeration tool
  README.md
Labels: hacktoberfest-accepted

#53 Added CTF Section
  README.md
Labels: hacktoberfest-accepted

#56 Add resource in Hacking Web Applications
  README.md
Labels: hacktoberfest-accepted

#55 Add resource in Hacking Mobile Platform
  README.md
Labels: hacktoberfest-accepted

#51 Adding CONTRIBUTING.md and imgs
  CONTRIBUTING.md
  img/compare&pull.png
  img/create pull request.png
  img/fork.png
  img/git Branch.png
  img/git add.png
  img/git clone.png
  img/git commit.png
  img/git push.png
  img/issue.png
  img/new issue.png
Labels: feature :rocket:
